### ISSUE TITLE
[comment] same need, same solution

### ISSUE THREAD

**Issue by setop** [gokrazy/freeze#5]
I came across the same need when [packaging a python application into a standalone folder](https://pyinstaller.org/).

I used the same trick : embed libs given by `ldd` with the exe into a tarball. Work pretty well.

Since I'm more a shell guy than a go guy, I used the following: 

```
# cd into dist folder
ldd $1       |  # list shared libs
  awk '$2 == "=>" { print $3 }' |  # format ldd output
  sort -u    |  # remove duplicated
  tar c -T - |  # tar from file list from stdin
  tar x         # untar in current folder
```

**Comment by stapelberg** [comment]
Cool, thanks for the note
